import { useRegisterUserMutation,
  useLoginUserMutation,
  useLogoutUserMutation,
  useCurrentUserQuery,
  useThemeUserMutation,
  useAvatarUserMutation,
  useHelpUserMutation,
  useGetBoardsQuery,
  useGetBoardByIdQuery,
  useAddBoardsMutation,
  useDeleteBoardByIdMutation,
  useUpdateBoardByIdMutation,
  useAddColumnMutation,
  useUpdateColumnByIdMutation,
  useDeleteColumnByIdMutation,
  useAddCardMutation,
  useUpdateCardByIdMutation,
  useDeleteCardByIdMutation,
  useUpdateCardColumnByIdMutation } from './API_Component/index';

export const API = {
   useRegisterUserMutation,
  useLoginUserMutation,
  useLogoutUserMutation,
  useCurrentUserQuery,
  useThemeUserMutation,
  useAvatarUserMutation,
  useHelpUserMutation,
  useGetBoardsQuery,
  useGetBoardByIdQuery,
  useAddBoardsMutation,
  useDeleteBoardByIdMutation,
  useUpdateBoardByIdMutation,
  useAddColumnMutation,
  useUpdateColumnByIdMutation,
  useDeleteColumnByIdMutation,
  useAddCardMutation,
  useUpdateCardByIdMutation,
  useDeleteCardByIdMutation,
  useUpdateCardColumnByIdMutation 
};