import {
  useRegisterMutation,
  useLogInMutation,
  useLogOutMutation,
  useGetCurrentUserQuery,
  useUpdateUserMutation,
  useThemeUserMutation,
  useUpdateAvatarMutation,
  useHelpUserMutation,
  useGetBoardsQuery,
  useGetBoardByIdQuery,
  useAddBoardsMutation,
  useDeleteBoardByIdMutation,
  useUpdateBoardByIdMutation,
  useAddColumnMutation,
  useUpdateColumnByIdMutation,
  useDeleteColumnByIdMutation,
  useGetAllCardsQuery,
  useAddCardMutation,
  useUpdateCardByIdMutation,
  useDeleteCardByIdMutation,
  useUpdateCardColumnByIdMutation,
} from './API_Component';

export const API = {
  useRegisterMutation,
  useLogInMutation,
  useLogOutMutation,
  useUpdateAvatarMutation,
  useGetCurrentUserQuery,
  useHelpUserMutation,
  useThemeUserMutation,
  useUpdateUserMutation,
  useGetBoardsQuery,
  useGetBoardByIdQuery,
  useAddBoardsMutation,
  useDeleteBoardByIdMutation,
  useUpdateBoardByIdMutation,
  useAddColumnMutation,
  useUpdateColumnByIdMutation,
  useDeleteColumnByIdMutation,
  useGetAllCardsQuery,
  useAddCardMutation,
  useUpdateCardByIdMutation,
  useDeleteCardByIdMutation,
  useUpdateCardColumnByIdMutation,
};
